-- Provisioned by docker-entrypoint-initdb.d on first container start.
-- The default database created from POSTGRES_DB env var is `mes_incidents`
-- (used by the n8n workflow's Postgres nodes). This script adds the second
-- database that n8n itself uses for internal state.

CREATE DATABASE n8n;

\connect mes_incidents

-- Schema for the AI Incident Intelligence workflow.
-- Tables are created idempotently so re-running init is safe.

CREATE TABLE IF NOT EXISTS incidents (
    id                   BIGSERIAL PRIMARY KEY,
    service              TEXT,
    severity             TEXT,
    category             TEXT,
    root_cause           TEXT,
    recommended_action   TEXT,
    auto_remediated      BOOLEAN DEFAULT FALSE,
    remediation_result   TEXT,
    detected_at          TIMESTAMPTZ,
    resolved_at          TIMESTAMPTZ,
    metrics_snapshot     JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS incidents_detected_at_idx ON incidents (detected_at DESC);
CREATE INDEX IF NOT EXISTS incidents_severity_idx    ON incidents (severity);
CREATE INDEX IF NOT EXISTS incidents_service_idx     ON incidents (service);

CREATE TABLE IF NOT EXISTS workflow_errors (
    id            BIGSERIAL PRIMARY KEY,
    workflow_id   TEXT,
    node_name     TEXT,
    error_message TEXT,
    stack         TEXT,
    payload       JSONB,
    occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS workflow_errors_occurred_at_idx ON workflow_errors (occurred_at DESC);

CREATE TABLE IF NOT EXISTS recovery_log (
    id            BIGSERIAL PRIMARY KEY,
    component     TEXT,             -- camera | iframe | ffmpeg | process | db
    target_id     TEXT,             -- camera id, process name, etc.
    action        TEXT,             -- restart | rate_limit | fail_over | escalate
    status        TEXT,             -- success | failed | partial | escalated
    detail        JSONB,
    occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS recovery_log_component_idx   ON recovery_log (component);
CREATE INDEX IF NOT EXISTS recovery_log_occurred_at_idx ON recovery_log (occurred_at DESC);

CREATE TABLE IF NOT EXISTS maintenance_tickets (
    id                  BIGSERIAL PRIMARY KEY,
    machine_id          TEXT,
    predicted_failure   TEXT,
    severity            TEXT,
    eta_hours           NUMERIC,
    recommended_action  TEXT,
    status              TEXT DEFAULT 'open',  -- open | acknowledged | resolved
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS maintenance_tickets_status_idx ON maintenance_tickets (status);

CREATE TABLE IF NOT EXISTS deployments (
    id            BIGSERIAL PRIMARY KEY,
    repo          TEXT,
    sha           TEXT,
    branch        TEXT,
    actor         TEXT,
    deployed_at   TIMESTAMPTZ,
    notes         TEXT
);

CREATE TABLE IF NOT EXISTS video_health_metrics (
    id            BIGSERIAL PRIMARY KEY,
    camera_id     TEXT,
    fps           NUMERIC,
    frame_age_ms  BIGINT,
    status        TEXT,
    sampled_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS video_health_sampled_at_idx ON video_health_metrics (sampled_at DESC);
CREATE INDEX IF NOT EXISTS video_health_camera_idx     ON video_health_metrics (camera_id);

-- ============================================================================
-- Phase 4b — AI subsystems
-- ============================================================================

-- CAPA (Corrective & Preventive Action) records generated by the CAPA AI agent.
CREATE TABLE IF NOT EXISTS capas (
    id                  BIGSERIAL PRIMARY KEY,
    incident_id         BIGINT REFERENCES incidents(id) ON DELETE SET NULL,
    title               TEXT,
    root_cause          TEXT,
    corrective_action   TEXT,
    preventive_action   TEXT,
    owner               TEXT,                 -- email or @slack-user
    due_at              TIMESTAMPTZ,
    severity            TEXT,
    status              TEXT DEFAULT 'open',  -- open | in_progress | closed | rejected
    ai_confidence       NUMERIC,              -- 0..1
    raw_agent_output    JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS capas_status_idx        ON capas (status);
CREATE INDEX IF NOT EXISTS capas_incident_id_idx   ON capas (incident_id);
CREATE INDEX IF NOT EXISTS capas_due_at_idx        ON capas (due_at);

-- Shift intelligence reports — one per shift end (3/day at IST 07/15/23).
CREATE TABLE IF NOT EXISTS shift_reports (
    id                BIGSERIAL PRIMARY KEY,
    shift_id          TEXT,                   -- e.g. "2026-05-20-A"
    shift_start       TIMESTAMPTZ NOT NULL,
    shift_end         TIMESTAMPTZ NOT NULL,
    incidents_count   INTEGER DEFAULT 0,
    auto_remediated   INTEGER DEFAULT 0,
    escalated         INTEGER DEFAULT 0,
    ng_count          INTEGER DEFAULT 0,
    ct_drift_alerts   INTEGER DEFAULT 0,
    top_issues        JSONB,                  -- [{ issue, count, trend }]
    operator_notes    JSONB,                  -- [{ operator, comment }]
    ai_summary        TEXT,
    ai_recommendations JSONB,                 -- [{ priority, action }]
    raw_agent_output  JSONB,
    generated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS shift_reports_generated_at_idx ON shift_reports (generated_at DESC);
CREATE INDEX IF NOT EXISTS shift_reports_shift_id_idx     ON shift_reports (shift_id);

-- Cross-source AI root-cause correlations.
-- Each row links a primary incident to N supporting signals from
-- PLC / RTSP / DB / server-load / NG / deployments.
CREATE TABLE IF NOT EXISTS correlations (
    id                  BIGSERIAL PRIMARY KEY,
    window_start        TIMESTAMPTZ NOT NULL,
    window_end          TIMESTAMPTZ NOT NULL,
    primary_incident_id BIGINT REFERENCES incidents(id) ON DELETE SET NULL,
    pattern_label       TEXT,                 -- AI-named pattern ("PLC stall after deploy")
    confidence          NUMERIC,              -- 0..1
    signal_count        INTEGER,
    sources_involved    TEXT[],               -- e.g. {'plc','db','deployments'}
    evidence            JSONB,                -- [{ source, signal_id, weight, summary }]
    suggested_action    TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS correlations_window_idx     ON correlations (window_end DESC);
CREATE INDEX IF NOT EXISTS correlations_confidence_idx ON correlations (confidence DESC);
CREATE INDEX IF NOT EXISTS correlations_pattern_idx    ON correlations (pattern_label);

-- AI video inspection results — placeholder for a future CV pipeline.
-- Today the workflow's Camera Incident Webhook can call into this from a
-- mock scorer; swap in a real CV service later without schema changes.
CREATE TABLE IF NOT EXISTS video_inspections (
    id            BIGSERIAL PRIMARY KEY,
    camera_id     TEXT,
    cycle_id      TEXT,                       -- production cycle id from MES
    frame_url     TEXT,                       -- where the frame snapshot lives
    verdict       TEXT,                       -- pass | fail | uncertain | error
    score         NUMERIC,                    -- 0..1
    model         TEXT,                       -- 'mock-v0' until real CV plugs in
    findings      JSONB,                      -- [{ class, bbox, confidence }]
    inspected_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS video_inspections_camera_idx   ON video_inspections (camera_id);
CREATE INDEX IF NOT EXISTS video_inspections_verdict_idx  ON video_inspections (verdict);
CREATE INDEX IF NOT EXISTS video_inspections_inspected_idx ON video_inspections (inspected_at DESC);
CREATE INDEX IF NOT EXISTS video_inspections_cycle_idx    ON video_inspections (cycle_id);

-- ============================================================================
-- Phase 5 — additional AI features
-- ============================================================================

-- Why-Machine-Failed Explainer — plain-language failure narratives generated
-- by the LLM after an incident is triaged. One row per (incident, explanation).
CREATE TABLE IF NOT EXISTS failure_explanations (
    id                  BIGSERIAL PRIMARY KEY,
    incident_id         BIGINT REFERENCES incidents(id) ON DELETE SET NULL,
    narrative           TEXT,
    factors             JSONB,    -- [{factor, weight, evidence}]
    confidence          NUMERIC,  -- 0..1
    suggested_action    TEXT,
    raw_agent_output    JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS failure_explanations_incident_idx ON failure_explanations (incident_id);
CREATE INDEX IF NOT EXISTS failure_explanations_created_idx  ON failure_explanations (created_at DESC);

-- Production cycle stream (one row per finished cycle per station) — feeds
-- the Bottleneck Detector. Populated by the MES line collector; here as
-- schema only so the workflow has somewhere to query against.
CREATE TABLE IF NOT EXISTS production_cycles (
    id              BIGSERIAL PRIMARY KEY,
    station_id      TEXT,
    cycle_id        TEXT,
    start_at        TIMESTAMPTZ,
    end_at          TIMESTAMPTZ,
    cycle_time_s    NUMERIC,
    parts_produced  INTEGER DEFAULT 1,
    ng_count        INTEGER DEFAULT 0,
    operator_id     TEXT,
    shift_id        TEXT
);
CREATE INDEX IF NOT EXISTS production_cycles_station_idx ON production_cycles (station_id);
CREATE INDEX IF NOT EXISTS production_cycles_start_idx   ON production_cycles (start_at DESC);
CREATE INDEX IF NOT EXISTS production_cycles_shift_idx   ON production_cycles (shift_id);

-- Bottleneck analyses — AI-identified slowest stations + loss projections.
CREATE TABLE IF NOT EXISTS bottleneck_analyses (
    id                       BIGSERIAL PRIMARY KEY,
    window_start             TIMESTAMPTZ NOT NULL,
    window_end               TIMESTAMPTZ NOT NULL,
    slowest_station          TEXT,
    bottleneck_factor        TEXT,             -- 'hydraulic_lag', 'operator_idle', etc.
    impact_summary           TEXT,
    projected_loss_parts     NUMERIC,
    projected_loss_currency  NUMERIC,
    confidence               NUMERIC,
    recommendations          JSONB,            -- [{priority, action}]
    raw_agent_output         JSONB,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bottleneck_analyses_window_idx ON bottleneck_analyses (window_end DESC);

-- Knowledge engine Q&A log — every operator query + AI answer + sources.
CREATE TABLE IF NOT EXISTS knowledge_qa (
    id           BIGSERIAL PRIMARY KEY,
    user_id      TEXT,
    question     TEXT,
    answer       TEXT,
    sources      JSONB,             -- list of incident_ids / capa_ids retrieved
    confidence   NUMERIC,
    feedback     INTEGER,           -- -1, 0, +1 thumbs
    asked_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS knowledge_qa_asked_idx ON knowledge_qa (asked_at DESC);
CREATE INDEX IF NOT EXISTS knowledge_qa_user_idx  ON knowledge_qa (user_id);

-- Spare part consumption history — populated each time maintenance burns a
-- spare part. Feeds the Spare Part Forecaster.
CREATE TABLE IF NOT EXISTS spare_parts_consumption (
    id           BIGSERIAL PRIMARY KEY,
    part_id      TEXT,
    part_name    TEXT,
    machine_id   TEXT,
    consumed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    quantity     INTEGER DEFAULT 1,
    reason       TEXT,                -- 'breakdown' | 'preventive' | 'restock'
    incident_id  BIGINT REFERENCES incidents(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS spare_parts_consumption_part_idx     ON spare_parts_consumption (part_id);
CREATE INDEX IF NOT EXISTS spare_parts_consumption_consumed_idx ON spare_parts_consumption (consumed_at DESC);
CREATE INDEX IF NOT EXISTS spare_parts_consumption_machine_idx  ON spare_parts_consumption (machine_id);

-- Spare-part failure forecasts — AI predictions of which parts fail next.
CREATE TABLE IF NOT EXISTS spare_forecasts (
    id                      BIGSERIAL PRIMARY KEY,
    part_id                 TEXT,
    part_name               TEXT,
    machine_id              TEXT,
    predicted_failure_date  DATE,
    days_until_failure      INTEGER,
    confidence              NUMERIC,
    reasoning               TEXT,
    recommended_action      TEXT,
    raw_agent_output        JSONB,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS spare_forecasts_created_idx ON spare_forecasts (created_at DESC);
CREATE INDEX IF NOT EXISTS spare_forecasts_part_idx    ON spare_forecasts (part_id);

-- Auto-created procurement requests (top picks from spare_forecasts).
CREATE TABLE IF NOT EXISTS procurement_requests (
    id           BIGSERIAL PRIMARY KEY,
    part_id      TEXT,
    part_name    TEXT,
    quantity     INTEGER,
    urgency      TEXT,                                            -- 'critical' | 'high' | 'normal'
    reason       TEXT,
    forecast_id  BIGINT REFERENCES spare_forecasts(id) ON DELETE SET NULL,
    status       TEXT DEFAULT 'pending',                          -- 'pending' | 'approved' | 'ordered' | 'received'
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS procurement_requests_status_idx  ON procurement_requests (status);
CREATE INDEX IF NOT EXISTS procurement_requests_urgency_idx ON procurement_requests (urgency);
